In [8]:
api_key = 'Q2ScRTFxPN3auqFzSwTARZjwyReBBqvGj6o62mwHs8dE3sq6ghkrwbcmAHIIFPB9'
secret = 'YbYojfUG1Ysk1Wg6yAHt1fZmQ47Jq8fKBkIXu3JZn41XzK1G9LnJHRiIyYhx8zWH'

In [9]:
from binance.client import Client

from binance.spot import Spot

from datetime import datetime, timedelta
import pandas as pd

# Initialize the Binance Spot client
client = Spot()


def get_from_api_historical_prices(list_of_symbol):
    historical_prices  = pd.DataFrame()

    for symbol in list_of_symbol:
        # Define the symbol and interval
        interval = Client.KLINE_INTERVAL_1MINUTE

        # Calculate the start and end times (6 months ago from now)
        end_time = client.get_server_time()['serverTime']
        start_time = end_time - (1 * 30 * 24 * 60 * 60 * 1000)  # 6 mois en millisecondes

        # Fetch historical klines data
        klines = client.get_historical_klines(symbol, interval, start_time, end_time)

        # Define the columns for the DataFrame
        spot_kline_cols = ['open_time', 'open', 'high', 'low', 'close', 'volume', 'close_time', 'quote_asset_volume', 'number_of_trades', 'taker_buy_base_asset_volume', 'taker_buy_quote_asset_volume', 'ignore']

        # Convert the klines data to a DataFrame
        df = pd.DataFrame(klines, columns=spot_kline_cols)
        df['Symbol'] = symbol
        df['timestamp'] = pd.to_datetime(df['open_time'], unit='ms')
        historical_prices = pd.concat([historical_prices, df])

    return historical_prices

In [10]:
client = Client(api_key, secret)
# Display the start and end timestamps
all_symbols = get_from_api_historical_prices(['ETHUSDT','BTCUSDT','DOGEUSDT'])

In [11]:
all_symbols.to_csv('../out/symbols_prices.csv', header =True, sep=';', encoding='utf-8', index=False)

In [12]:
all_symbols.head()

,open_time,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,taker_buy_quote_asset_volume,ignore,Symbol,timestamp
0,1716485760000,3818.39000000,3824.00000000,3817.57000000,3823.99000000,308.93120000,1716485819999,1180332.10137300,738,211.69940000,808810.98526400,0,ETHUSDT,2024-05-23 17:36:00
1,1716485820000,3823.99000000,3824.00000000,3816.02000000,3817.73000000,271.40470000,1716485879999,1036755.73599900,629,77.89080000,297494.35312700,0,ETHUSDT,2024-05-23 17:37:00
2,1716485880000,3817.73000000,3817.73000000,3810.81000000,3813.64000000,401.67410000,1716485939999,1531731.93037300,955,157.50030000,600517.56545100,0,ETHUSDT,2024-05-23 17:38:00
3,1716485940000,3813.65000000,3816.77000000,3812.29000000,3812.89000000,194.53670000,1716485999999,742065.73676600,499,90.29000000,344397.83769900,0,ETHUSDT,2024-05-23 17:39:00
4,1716486000000,3812.88000000,3817.15000000,3812.88000000,3815.69000000,114.08970000,1716486059999,435281.03045400,378,51.56620000,196718.95783300,0,ETHUSDT,2024-05-23 17:40:00